language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - git

stages:
  - name: tests
  - name: lint

jobs:
    include:
      - stage: tests
        script:
          - npm run test
        after_success:
          - npm run report-coverage
          - codecov
      - stage: lint
        script:
          - npm run jshint

