language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

addons:
  apt:
    packages:
      - git

install:
  - npm install -g codecov
  - npm install
  - touch .env

stages:
    - name: tests
      script:
        - npm run test
      after_success:
        - npm run report-coverage
        - codecov
    - name: lint
      script:
        - npm run jshint


