language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

addons:
  mariadb: '10.3'
  apt:
    packages:
      - git

stages:
  - name: tests
  - name: lint

jobs:
    include:
      - stage: tests
        env:
          - DB_TEST_HOST=127.0.0.1
          - DB_TEST_USER=root
          - DB_TEST_PASS=
          - DB_TEST_DB=deployer__test
        before_script:
          - mysql -e 'CREATE DATABASE IF NOT EXISTS deployer__test;'
          - npm run migrate:test
        script:
          - npm run test
        after_success:
          - npm run report-coverage
          - codecov
      - stage: lint
        script:
          - npm run jshint

